import { supabase } from '../supabase';
import { DoctorConfig, Patient, Prescription, PrescriptionItem } from '../types';

export interface UserProfile { uid:string; email:string; role:'doctor'|'secretary'; doctorUid:string; clinicId:string; createdAt:string }
const fail=(e:any)=>{if(e)throw new Error(e.message||String(e));};
export async function setupUserAndGetProfile(uid:string,email:string):Promise<UserProfile>{
 let {data:m,error}=await supabase.from('clinic_memberships').select('clinic_id,role').eq('user_id',uid).maybeSingle(); fail(error);
 if(!m){const token=new URLSearchParams(location.search).get('invite');if(token){const r=await supabase.rpc('claim_secretary_invitation',{token});fail(r.error);}else{const r=await supabase.rpc('bootstrap_doctor');fail(r.error);} const retry=await supabase.from('clinic_memberships').select('clinic_id,role').eq('user_id',uid).single();fail(retry.error);m=retry.data;}
 const doctor=await supabase.from('clinic_memberships').select('user_id').eq('clinic_id',m.clinic_id).eq('role','doctor').single();fail(doctor.error);
 return{uid,email:email.toLowerCase(),role:m.role,doctorUid:doctor.data.user_id,clinicId:m.clinic_id,createdAt:new Date().toISOString()};
}
export async function fetchDoctorConfig(clinicId:string){const r=await supabase.from('doctor_configs').select('config').eq('clinic_id',clinicId).maybeSingle();fail(r.error);return(r.data?.config as DoctorConfig)||null;}
export async function saveDoctorConfig(clinicId:string,config:DoctorConfig){const r=await supabase.from('doctor_configs').update({config}).eq('clinic_id',clinicId);fail(r.error);}
export async function createSecretaryAccount(_doctorUid:string,email:string){const r=await supabase.rpc('create_secretary_invitation',{invitee_email:email});fail(r.error);return `${location.origin}?invite=${r.data}`;}
export async function fetchSecretaries(_doctorUid:string):Promise<UserProfile[]>{const me=await supabase.auth.getUser();const membership=await supabase.from('clinic_memberships').select('clinic_id').eq('user_id',me.data.user?.id).single();fail(membership.error);const r=await supabase.from('clinic_memberships').select('user_id,role,profiles(email,created_at)').eq('clinic_id',membership.data.clinic_id).eq('role','secretary');fail(r.error);return(r.data||[]).map((x:any)=>({uid:x.user_id,email:x.profiles.email,role:'secretary',doctorUid:me.data.user!.id,clinicId:membership.data.clinic_id,createdAt:x.profiles.created_at}));}
export async function deleteSecretaryProfile(id:string){const r=await supabase.rpc('remove_secretary',{member_id:id});fail(r.error);}
function patientRow(p:Patient,clinicId:string){const {id,name_first,name_last,birth_date,gender,weight,allergies,phone,...clinical_data}=p;return{id,clinic_id:clinicId,name_first,name_last,birth_date,gender,weight:weight??null,allergies,phone:phone??null,clinical_data};}
export async function savePatient(p:Patient,clinicId:string){const r=await supabase.from('patients').upsert(patientRow(p,clinicId));fail(r.error);}
export async function deletePatient(id:string){const r=await supabase.from('patients').delete().eq('id',id);fail(r.error);}
export async function savePrescriptionBundle(p:Prescription,items:PrescriptionItem[],clinicId:string){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error('AUTH_REQUIRED');const final={...p,doctor_id:user.id};const row={id:p.id,clinic_id:clinicId,patient_id:p.patient_id,doctor_id:user.id,prescription_number:p.prescription_number,prescription_date:p.prescription_date,status:'draft',snapshot:{...final,status:'draft'},signed_at:null,created_at:p.created_at,updated_at:p.updated_at};let r=await supabase.from('prescriptions').upsert(row);fail(r.error);r=await supabase.from('prescription_items').delete().eq('prescription_id',p.id);fail(r.error);if(items.length){r=await supabase.from('prescription_items').insert(items.map(x=>({id:x.id,prescription_id:p.id,line_order:x.line_order,payload:{...x,prescription_id:p.id},created_at:x.created_at,updated_at:x.updated_at})));fail(r.error);}if(p.status!=='draft'){r=await supabase.from('prescriptions').update({status:p.status,snapshot:final,signed_at:p.signed_at??new Date().toISOString()}).eq('id',p.id);fail(r.error);}return {prescription:final,items};}
export async function loadClinicalData(profile:UserProfile){const [c,p,r,i]=await Promise.all([fetchDoctorConfig(profile.clinicId),supabase.from('patients').select('*').eq('clinic_id',profile.clinicId),profile.role==='doctor'?supabase.from('prescriptions').select('*').eq('clinic_id',profile.clinicId):Promise.resolve({data:[],error:null}),profile.role==='doctor'?supabase.from('prescription_items').select('*,prescriptions!inner(clinic_id)').eq('prescriptions.clinic_id',profile.clinicId):Promise.resolve({data:[],error:null})]);fail((p as any).error);fail((r as any).error);fail((i as any).error);return{doctorConfig:c,patients:((p as any).data||[]).map((x:any)=>({...x,...x.clinical_data,clinical_data:undefined,clinic_id:undefined})),prescriptions:((r as any).data||[]).map((x:any)=>x.snapshot),prescriptionItems:((i as any).data||[]).map((x:any)=>x.payload)};}
export function subscribeClinicalData(profile:UserProfile,onChange:()=>void){const channel=supabase.channel(`clinic:${profile.clinicId}`).on('postgres_changes',{event:'*',schema:'public',table:'doctor_configs',filter:`clinic_id=eq.${profile.clinicId}`},onChange).on('postgres_changes',{event:'*',schema:'public',table:'patients',filter:`clinic_id=eq.${profile.clinicId}`},onChange);if(profile.role==='doctor')channel.on('postgres_changes',{event:'*',schema:'public',table:'prescriptions',filter:`clinic_id=eq.${profile.clinicId}`},onChange);channel.subscribe();return()=>{void supabase.removeChannel(channel);};}
export async function deleteUserAccount(_uid:string,_role:'doctor'|'secretary'){const r=await supabase.rpc('delete_own_account');fail(r.error);await supabase.auth.signOut();}
